In [11]:
import numpy as np

In [3]:
# our data set
training_data = [
    ['Sweet', 'Green', 3, 'Apple'],
    ['Sweet', 'Green', 4, 'Apple'],
    ['Sweet', 'Yellow', 3, 'Apple'],
    ['Sour', 'Green', 2, 'Apple'],
    ['Sour', 'Green', 3, 'Apple'],
    ['Sweet', 'Purple', 1, 'Grape'],
    ['Sweet', 'Red', 1, 'Grape'],
    ['Sweet', 'Red', 1, 'Grape'],
    ['Sour', 'Yellow', 3, 'Lemon'],
    ['Sweet', 'Yellow', 3, 'Lemon'],
    ['Sour', 'Yellow', 2, 'Lemon']
]

In [71]:
dataSet=np.array(training_data)

In [6]:
print(dataSet)

[['Sweet' 'Green' '3' 'Apple']
 ['Sweet' 'Green' '4' 'Apple']
 ['Sweet' 'Yellow' '3' 'Apple']
 ['Sour' 'Green' '2' 'Apple']
 ['Sour' 'Green' '3' 'Apple']
 ['Sweet' 'Purple' '1' 'Grape']
 ['Sweet' 'Red' '1' 'Grape']
 ['Sweet' 'Red' '1' 'Grape']
 ['Sour' 'Yellow' '3' 'Lemon']
 ['Sweet' 'Yellow' '3' 'Lemon']
 ['Sour' 'Yellow' '2' 'Lemon']]


In [72]:
# features
X=dataSet[:,0:3]
# labels
y=dataSet[:,3]

In [73]:
print(X)

[['Sweet' 'Green' '3']
 ['Sweet' 'Green' '4']
 ['Sweet' 'Yellow' '3']
 ['Sour' 'Green' '2']
 ['Sour' 'Green' '3']
 ['Sweet' 'Purple' '1']
 ['Sweet' 'Red' '1']
 ['Sweet' 'Red' '1']
 ['Sour' 'Yellow' '3']
 ['Sweet' 'Yellow' '3']
 ['Sour' 'Yellow' '2']]


In [12]:
from sklearn import tree

In [13]:
# initializing the classifier object
DTreeClassifier = tree.DecisionTreeClassifier()
# initializing the regresor object
DTreeRegssor = tree.DecisionTreeRegressor()

In [88]:
# Because the system noly works with float numbers 
# we have to convert string values to numbers here 
# we used the one hot encoding
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
labels_1hot=encoder.fit_transform(y)
labels_1hot=[np.where(r==1)[0][0] for r in labels_1hot]

# new trainig set with features of number type
X_1hot=np.empty([11,3])

X_1hot[:,0]=np.reshape(encoder.fit_transform(X[:,0]),(1,11))

a=encoder.fit_transform(X[:,1])
X_1hot[:,1]=[np.where(r==1)[0][0] for r in a]

X_1hot[:,2]=X[:,2]

print(labels_1hot)
print(y)
print(X_1hot)
print(X)

[0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2]
['Apple' 'Apple' 'Apple' 'Apple' 'Apple' 'Grape' 'Grape' 'Grape' 'Lemon'
 'Lemon' 'Lemon']
[[1. 0. 3.]
 [1. 0. 4.]
 [1. 3. 3.]
 [0. 0. 2.]
 [0. 0. 3.]
 [1. 1. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [0. 3. 3.]
 [1. 3. 3.]
 [0. 3. 2.]]
[['Sweet' 'Green' '3']
 ['Sweet' 'Green' '4']
 ['Sweet' 'Yellow' '3']
 ['Sour' 'Green' '2']
 ['Sour' 'Green' '3']
 ['Sweet' 'Purple' '1']
 ['Sweet' 'Red' '1']
 ['Sweet' 'Red' '1']
 ['Sour' 'Yellow' '3']
 ['Sweet' 'Yellow' '3']
 ['Sour' 'Yellow' '2']]


In [89]:
DTreeClassifier.fit(X_1hot,labels_1hot)
DTreeRegssor.fit(X_1hot,labels_1hot)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [106]:
# test sample
X_test=[[1,0,2],[1,1,0.5],[1,2,1.8]]
y_test=[0,1,0] # Apple Grape Apple

In [114]:
clf_result=DTreeClassifier.predict(X_test)
rgs_result=DTreeRegssor.predict(X_test)

In [115]:
print("Classifier : {}".format(clf_result))
print("Regressor : {}".format(rgs_result))

Classifier : [0 1 0]
Regressor : [0. 1. 1.]


In [116]:
from sklearn.metrics import accuracy_score

In [117]:
acc_clf=accuracy_score(clf_result, y_test)
acc_reg=accuracy_score(rgs_result, y_test)

In [118]:
print("Classifier accuracy : {}".format(acc_clf))
print("Regressor accuracy : {}".format(acc_reg))

Classifier accuracy : 1.0
Regressor accuracy : 0.6666666666666666


# classifier is probably overfitting the training set